CREATE TABLE DataMart_Log.Rules_Engine_Processing_Log
(ProcName VARCHAR(200) NOT NULL CONSTRAINT PK_Rules_Engine_Processing_Log PRIMARY KEY CLUSTERED,
StartTime DATETIME2,
EndTime DATETIME2 NULL,
RunTime_sec DECIMAL(38,6) NULL,
RunTime VARCHAR (20) NULL,
ProcDefinition VARCHAR(MAX) NULL,
QueryPlan XML NULL,
Error VARCHAR(1000) NULL,
ValidFrom DATETIME2 GENERATED ALWAYS AS ROW START,
ValidTo DATETIME2 GENERATED ALWAYS AS ROW END,
PERIOD FOR SYSTEM_TIME(ValidFrom, ValidTo)
)
WITH (SYSTEM_VERSIONING = ON
(HISTORY_TABLE = DataMart_Log.Rules_Engine_Processing_Log_History,
HISTORY_RETENTION_PERIOD = 2 WEEKS)
);